# Generated by Django 5.0.3 on 2024-04-09 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0023_profilepic_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='shopsignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('shop_pic', models.ImageField(upload_to='shop/shoppic')),
                ('shop_license', models.ImageField(upload_to='shop/license')),
                ('permission', models.CharField(choices=[('a', 'approved'), ('p', 'pending'), ('r', 'rejected')], default='p', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Out for shipping', 'Out for shipping'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='pending', max_length=150),
        ),
        migrations.CreateModel(
            name='shop_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shp_owner', models.CharField(max_length=50)),
                ('owner_pic', models.ImageField(upload_to='shop/owners')),
                ('shop_description', models.TextField()),
                ('my_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.shopsignup')),
            ],
        ),
    ]
