# Generated by Django 5.0.3 on 2024-04-13 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0024_shopsignup_alter_order_status_shop_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopsignup',
            name='permission',
            field=models.CharField(choices=[('aproved', 'approved'), ('pending', 'pending'), ('rejected', 'rejected')], default='p', max_length=100),
        ),
    ]
