# Generated by Django 4.2.6 on 2024-04-15 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0025_alter_shopsignup_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='my_shop',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app1.shopsignup'),
        ),
        migrations.AddField(
            model_name='products',
            name='stck',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='shopsignup',
            name='permission',
            field=models.CharField(choices=[('aproved', 'approved'), ('pending', 'pending'), ('rejected', 'rejected')], default='pending', max_length=100),
        ),
    ]
