# Generated by Django 4.2.6 on 2024-04-16 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0026_products_my_shop_products_stck_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='shopPasswordReset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.shopsignup')),
            ],
        ),
        migrations.CreateModel(
            name='shopmsg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopname', models.CharField(max_length=50)),
                ('shop_pic', models.ImageField(upload_to='shop/shoppic')),
                ('shop_license', models.ImageField(upload_to='shop/license')),
                ('my_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.shopsignup')),
            ],
        ),
    ]
