# Generated by Django 4.2.6 on 2024-04-22 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0027_shoppasswordreset_shopmsg'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='stck_chnge',
            field=models.BooleanField(default=False),
        ),
    ]
